[env]
TERM = "xterm-256color"


[[colors.indexed_colors]]
color = "0xf28fad"
index = 16

[[colors.indexed_colors]]
color = "0xb4637a"
index = 17

[colors.bright]
black = "0x585b70"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xa6adc8"
yellow = "0xf9e2af"

[colors.normal]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xbac2de"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[cursor]
style = "Beam"

[font]
size = 9.0

[font.bold]
family = "Maple Mono"

[font.bold_italic]
family = "Maple Mono"

[font.italic]
family = "Maple Mono"

[font.normal]
family = "Maple Mono"

[window]
opacity = 0.8

[window.padding]
x = 0
y = 4
