[[themes]]
name = "default"
[themes.palette]
background = "#141b1e"
foreground = "#dadada"
black = "#232a2d"
blue = "#67b0e8"
cyan = "#6cbfbf"
green = "#8ccf7e"
magenta = "#c47fd5"
red = "#e57474"
white = "#b3b9b8"
yellow = "#e5c76b"
bright_black = "#2d3437"
bright_blue = "#71baf2"
bright_cyan = "#67cbe7"
bright_green = "#96d988"
bright_magenta = "#ce89df"
bright_red = "#ef7e7e"
bright_white = "#bdc3c2"
bright_yellow = "#f4d67a"

[themes.component_style]
selection = { bg = "#2d3437", modifiers = ["Bold"] }
