[[themes]]
name = "default"
[themes.palette]
background = "#1a1b26"
foreground = "#a9b1d6"
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#73daca"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"
bright_black = "#414868"
bright_blue = "#7aa2f7"
bright_cyan = "#7dcfff"
bright_green = "#73daca"
bright_magenta = "#bb9af7"
bright_red = "#f7768e"
bright_white = "#c0caf5"
bright_yellow = "#e0af68"

[themes.component_style]
selection = { bg = "#28344a", modifiers = ["Bold"] }
